name: Build Samsung Kernel (Galaxy s20fe)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v7

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bison \
            flex \
            libssl-dev \
            libncurses-dev \
            bc \
            cpio \
            zip \
            unzip \
            zstd \
            patchelf \
            curl \
            git

      - name: ksu
        run: |
         wget https://raw.githubusercontent.com/rksuorg/kernel_patches/refs/heads/master/manual_hook/kernel-4.19_5.4.patch
         patch -p1 < kernel-4.19_5.4.patch
         curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
            
      - name: Configure and Build Kernel
        run: bash build_kernel.sh

      - name: AnyKernel3
        run: git clone https://github.com/redmax19/AnyKernel3.git

      - name: Build AnyKernel package
        run: |
         cp out/arch/arm64/boot/Image AnyKernel3/Image
         cd AnyKernel3
         zip -r9 "../alessandro r8s KernelSU.zip" * -x .git .github README.md *placeholder

      - name: Upload AnyKernel package
        uses: actions/upload-artifact@v7
        with:
         name: AnyKernel package
         path: alessandro r8s KernelSU.zip

  
